apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-python-scheduler
  template:
    metadata:
      labels:
        app: simple-python-scheduler
    spec:
      containers:
      - name: simple-python-scheduler
        image: {{ .Values.image }}
        env:
          - name: NAMESPACE
            value: {{ .Values.monitoredNamespace }}
