name: docker-build

on:
  workflow_dispatch:

jobs:

  build-image:
    runs-on: ubuntu-latest
    steps:
    - name: Login to registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Declare git tag as environment variable
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    - name: Build Simple Python Scheduler image
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        context: .
        tags: simple-python-scheduler:${{ env.sha_short }},simple-python-scheduler:latest
        cache-from: type=gha,scope=buildkit-ci
        cache-to: type=gha,mode=max,scope=buildkit-ci
